apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::216444449243:role/eksctl-myTestCluster-nodegroup-ng-NodeInstanceRole-1BHD38FD35X5P
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::216444449243:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-06-24T06:22:45Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1661"
  uid: e70337f1-87e6-4508-8641-f8507a30d481
